modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge.  The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="fireflies" #mandatory
version="1.4.1" #mandatory
displayName="Fireflies" #mandatory
logoFile="examplemod.png" #optional
credits="Credits goes to Kaupenjoe for his amazing tutorials!" #optional
authors="DoctorG_Mystery" #optional
description='''
Nothing much to say here... Fireflies ya know.
'''

[[dependencies.fireflies]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fireflies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fireflies]]
    modId="citadel"
    mandatory=true
    versionRange="[1.9.5,)"
    ordering="NONE"
    side="BOTH"
