modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge.  The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="fireflies" #mandatory
version="1.0" #mandatory
displayName="Fireflies" #mandatory
logoFile="examplemod.png" #optional
credits="Credits goes to Kaupenjoe for his amazing tutorials!" #optional
authors="DoctorG_Mystery" #optional
description='''
Nothing much to say here... Fireflies ya know.
'''

[[dependencies.fireflies]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fireflies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
