modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge.  The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="All rights reserved"
issueTrackerURL="https://github.com/DoctorGMystery/Fireflies/issues" #optional

[[mods]] #mandatory
modId="fireflies" #mandatory
version="1.11.0" #mandatory
displayName="Fireflies" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/nights-light" #optional
logoFile="thumbnail.png" #optional
credits="Credits goes to Kaupenjoe for his amazing tutorials!" #optional
authors="DoctorG_Mystery" #optional
description='''
Not much to say here... Fireflies ya know.
'''

[[dependencies.fireflies]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fireflies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fireflies]]
    modId="citadel"
    mandatory=true
    versionRange="[2.4.2,)"
    ordering="NONE"
    side="BOTH"
